#! /usr/bin/env bash

ESC=$'\x1b'

# I want 3 stacks of chips
# Far left are Blue = 10. Max of 9
blue=21
# Middle is yellow = 100. Max of 9
yellow=11
# Far right is purple = 1000. Max of 9
 purple=55
# Which means the max bank value to show without breaking is 9999

	
function print_art() {
	local art=$1
	local start_x=$2
	local start_y=$3
	
	while IFS= read -r line; do
		tput cup $start_y $start_x
		echo -n "$line"
		((start_y++))
	done <<< "$art"
}

function art_width() {
	local art=$1
	local max=0
	local current_line_len=
	while read line; do

		current_line_len=${#line}
		if [[ $current_line_len -gt $max ]]; then
			max=$current_line_len
		fi
	done <<< $art
	echo "$max"
}

function art_height() {
	local art=$1
	local count=0

	while read line; do
		((count++))
	done
	echo "$count"
}

function print_chip_stack() {
	local count=$1
	local x=$2
	local y=$3

	
	#Clean up
	tput sgr0
	local clean_y=$y
	for i in $(seq 1 9); do
		tput cup $clean_y $x
		echo -n "                  "
		((clean_y--))
	done


	#Starting with far right, the 1000s
	local thous_y=$y
	while [[ "$count" -ge 1000 ]]; do
		tput cup $thous_y $((x+12)) 
		echo -n "$ESC[38;5;${purple}m"
		echo -n "$CHIP"
		count=$(( $count - 1000 ))
		((thous_y--))
	done

	#Now middle, the 100s
	local hund_y=$y
	while [[ "$count" -ge 100 ]]; do
		tput cup $hund_y $((x+6)) 
		echo -n "$ESC[38;5;${yellow}m"
		echo -n "$CHIP"
		count=$(( $count - 100 ))
		((hund_y--))
	done

	#Now middle, the 10s
	local ten_y=$y
	while [[ "$count" -ge 10 ]]; do
		tput cup $ten_y $((x)) 
		echo -n "$ESC[38;5;${blue}m"
		echo -n "$CHIP"
		count=$(( $count - 10 ))
		((ten_y--))
	done

	tput sgr0
}

function print_bet() {
	local bet=$1
	
	# Set background to green, I am not sure if this works
	echo -n "$ESC[48;5;2m"

	if [[ "$bet" -ge 1000 ]]; then
		# Bet is >= 1000 purple chip
		echo -n "$ESC[38;5;${purple}m"
	elif [[ "$bet" -ge 100 ]]; then
		# Bet is < 1000 yellow chip
		echo -n "$ESC[38;5;${yellow}m"
	elif [[ "$bet" -ge 10 ]]; then
		#Bet is < 100, blue chip
		echo -n "$ESC[38;5;${blue}m"

	fi
	
		
	local starting_col=$(($LINES - 31))
	local a_width=$(art_width "$TOP_CHIP")
	local center_col=$(( ($COLUMNS/2) -1))
	local starting_x="$((center_col-(art_width/2)))"
	print_art "$TOP_CHIP" $starting_x $starting_col
	
	tput sgr0
}

function print_card() {
	local card=$1
	local x=$2
	local y=$3
	tput cup $y $x
	echo -n "└───┘"
	tput cup $(($y-1)) $x
	local card_digit=$(printf '%-2s' "${card:0:-1}")
	local card_suit="${card:0-1}"

	case $card_suit in 
		"S")
			echo -n "│${card_digit}♠│"
			;;
		"C")
			echo -n "│${card_digit}♣│"
			;;
		"D")
			echo -n "│${card_digit}♦│"
			;;
		"H")
			echo -n "│${card_digit}♥│"
			;;
		*)
			echo -n "|███|"
			;;
	esac
	tput cup $((y-2)) $x
	echo -n "┌───┐"

}

IFS= read -d '' -r CARD_BACK <<"EOF"
┌───┐
|███|
└───┘
EOF

IFS= read -d '' -r BLACKJACK_ART <<"EOF"
______ _            _    _            _    
| ___ \ |          | |  (_)          | |   
| |_/ / | __ _  ___| | ___  __ _  ___| | __
| ___ \ |/ _` |/ __| |/ / |/ _` |/ __| |/ /
| |_/ / | (_| | (__|   <| | (_| | (__|   < 
\____/|_|\__,_|\___|_|\_\ |\__,_|\___|_|\_|
                       _/ |                
                      |__/                 
EOF

IFS= read -d '' -r CHIP <<"EOF"
██████
EOF

IFS= read -d '' -r TOP_CHIP <<"EOF"
 ▄▄▄ 
█████
█████
 ▀▀▀ 
EOF

IFS= read -d '' -r INPUT_BOX<<"EOF"
┌──────────────────────┐
│                      │
└──────────────────────┘
EOF

IFS= read -d '' -r MESSAGE_BOX<<"EOF"
┌─────────────────────────────────────────┐
│                                         │
│                                         │
│                                         │
│                                         │
│                                         │
│        ~Press Enter to Continue~        │
└─────────────────────────────────────────┘
EOF


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	echo " Testing art"

	print_card "AS" 20 20
	print_card "10D" 25 25
fi
