#!/usr/bin/env bash

. ./deck
. ./card

# Constants
NUM_OF_DECKS=1

function end_logic() {
	local player_total=$1
	local dealer_total=$2
	
	echo "player_total: $player_total"
	echo "dealer_total: $dealer_total"

	if [[ $player_total -gt 21 ]]; then
		echo "Player busted, dealer wins"
	elif [[ $dealer_total -gt 21 ]]; then
		echo "Dealer busted, player wins"
	elif [[ $player_total == $dealer_total ]]; then
		echo "Draw, it is a push"
	elif [[ $player_total -gt $dealer_total ]]; then
		echo "Player wins!"
	elif [[ $player_total -lt $dealer_total ]]; then
		echo "Dealer wins :("
	else
		echo "Something went wrong"
		return 1
	fi	
	return 0

}

function initial_deal() {
	local -n deck_ref=$1

	local -n dealer_hand_ref=$2
	local -n player_hand_ref=$3
	
	draw deck dealer_card_1_ref
	draw deck player_card_1_ref
	draw deck dealer_card_2_ref
	draw deck player_card_2_ref

	dealer_hand=( $dealer_card_1_ref $dealer_card_2_ref )
	player_hand=( $player_card_1_ref $player_card_2_ref )
}

function dealer_draw() {
	local -n deck_ref=$1
	local -n dealer_hand_ref=$2
	local dealer_hand_arr=("${dealer_hand_ref[@]}")

	echo "Dealer reveals their card, they have a ${dealer_hand_arr[0]}"
	local dealer_total=$(hand_total "${dealer_hand_arr[@]}")
	while [ $dealer_total -le 16 ]; do

		
		local new_card="${deck_ref[0]}"
		deck_ref=( "${deck_ref[@]:1}" )

		echo "Dealer drew: $new_card"
		dealer_hand_arr+=($new_card)
		local dealer_total=$(hand_total "${dealer_hand_arr[@]}")
		echo "Dealer total: $dealer_total"
	done
	dealer_hand_ref=("${dealer_hand_arr[@]}")
}


function main() {
	deck=( $(draw_deck $NUM_OF_DECKS) )
	local busted="false"
	#echo "deck: ${deck[@]}"
	
	initial_deal deck dealer_hand player_hand

	local player_hand=(${player_hand[@]})
	local dealer_hand=(${dealer_hand[@]})
	echo "Dealer has ${dealer_hand[1]} showing"
	echo "You have ${player_hand[@]}"
	
#	echo "deck: ${deck[@]}"
	while true; do
		if [[ $busted == "false" ]]; then
			printf 'Action: '
			local total=0
			read -r response;
		else
			response="stand"
		fi
		case $response in
			"hit"|"h"|"draw"|"d"|"y"|"yes")
				draw deck card
				local player_hand+=($card)
				echo "Player hand = ${player_hand[@]}"
				if [[ -z "${deck[@]}" ]]; then
					echo "deck is empty"
					deck=( $(draw_deck $NUM_OF_DECKS) )
				fi

				local total=$(hand_total "${player_hand[@]}")
				if [[ $total -gt 21 ]]; then
					echo "You have busted with a value of $total"
					local busted="true"
				fi
				;;

			"stand"|"stop"|"s")
				local total=$(hand_total "${player_hand[@]}")
				echo "You are standing with a value of $total"
				
				dealer_draw deck dealer_hand
				local dealer_total=$(hand_total "${dealer_hand[@]}")
				end_logic $total $dealer_total  
				
				return 0
				
				;;
			"q"|"quit"|"exit")
				echo "leaving the program"
				return 0
				;;
			*)
				printf "Valid command not found\n'hit' or 'h' to add a card\n'stand' or 's' to stand\n'quit' or 'q' to quit the program\n"
		esac
	done
	return 0

}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        echo "Running BlackJack"
	main
fi

