#!/usr/bin/env bash

. ./deck
. ./card
. ./helper

# Constants
NUM_OF_DECKS=1

function end_logic() {
	# I am taking the return code to mean if the code failed to run
	# But rather the result of the end 
	# 2 	= player wins
	# 3 	= dealer wins
	# 4 	= push
	# 21	= blackjack win (we have fun here)
	# I could do it a different way, but this will help me learn some bash things
	local -n player_hand_ref=$1	
	local -n dealer_hand_ref=$2
	debug "What is up with these: "
	debug "Player hand ${player_hand_ref[@]}"
	debug "Dealer hand ${dealer_hand_ref[@]}"	
	local player_total=$(hand_total "${player_hand_ref[@]}")
	local dealer_total=$(hand_total "${dealer_hand_ref[@]}")

	# Special logic if there is a blackjack involved
	local player_bj=$(is_blackjack "${player_hand_ref[@]}")
	local dealer_bj=$(is_blackjack "${dealer_hand_ref[@]}")

	# Making it 1 string so I can use a CASE statement rather than a nest of if else
	local concat="${player_bj}${dealer_bj}"
	debug "Concatinated player_blackjack dealer_blackjack results: $concat"
	case $concat in 
		"truetrue")
			# Both blackjack, push
			return 4
			;;
		"truefalse")
			# You got blackjack, dealer does not
			return 21
			;;
		"falsetrue")
			# Dealer has blackjack, you do not
			return 3
			;;
		"falsefalse")
			# Nothing special here
			;;
	esac


	
	#echo "player_total: $player_total"
	#echo "dealer_total: $dealer_total"
	
	debug "Totals: \n\tPlayer: $player_total \n\tDealer: $dealer_total"

	if [[ $player_total -gt 21 ]]; then
		echo "Player busted, dealer wins"
		return 3
	elif [[ $dealer_total -gt 21 ]]; then
		echo "Dealer busted, player wins"
		return 2
	elif [[ $player_total == $dealer_total ]]; then
		echo "Draw, it is a push"
		return 4
	elif [[ $player_total -gt $dealer_total ]]; then
		echo "Player wins!"
		return 2
	elif [[ $player_total -lt $dealer_total ]]; then
		echo "Dealer wins :("
		return 3
	else
		echo "Something went wrong"
		return 1
	fi	

}

function initial_deal() {
	local -n deck_ref=$1

	local -n dealer_hand_ref=$2
	local -n player_hand_ref=$3
	
	draw deck player_card_1_ref
	draw deck dealer_card_1_ref
	draw deck player_card_2_ref
	draw deck dealer_card_2_ref

	dealer_hand=( $dealer_card_1_ref $dealer_card_2_ref )
	player_hand=( $player_card_1_ref $player_card_2_ref )
}

function dealer_draw() {
	local -n deck_ref=$1
	local -n dealer_hand_ref=$2
	local dealer_hand_arr=("${dealer_hand_ref[@]}")

	echo "Dealer reveals their card, they have a ${dealer_hand_arr[0]}"
	local dealer_total=$(hand_total "${dealer_hand_arr[@]}")
	while [ $dealer_total -le 16 ]; do

		
		local new_card="${deck_ref[0]}"
		deck_ref=( "${deck_ref[@]:1}" )

		echo "Dealer drew: $new_card"
		dealer_hand_arr+=($new_card)
		local dealer_total=$(hand_total "${dealer_hand_arr[@]}")
	done
	echo "Dealer total: $dealer_total"
	dealer_hand_ref=("${dealer_hand_arr[@]}")
}




function game() {
	deck=( $(draw_deck $NUM_OF_DECKS) )
	local stop_draw="false"
	debug "deck before drawing: ${deck[@]}"
	
	initial_deal deck dealer_hand player_hand

	local player_hand=(${player_hand[@]})
	local dealer_hand=(${dealer_hand[@]})
	echo "Dealer has ${dealer_hand[1]} showing"
	echo "You have ${player_hand[@]}"
	
	while true; do
		if [[ $stop_draw == "false" ]]; then
			printf 'Action: '
			local total=0
			read -r response;
		else
			response="stand"
		fi
		case $response in
			"hit"|"h"|"draw"|"d"|"y"|"yes")
				draw deck card
				local player_hand+=($card)
				echo "Player hand = ${player_hand[@]}"
				if [[ -z "${deck[@]}" ]]; then
					echo "deck is empty"
					deck=( $(draw_deck $NUM_OF_DECKS) )
				fi

				local total=$(hand_total "${player_hand[@]}")
				if [[ $total -gt 21 ]]; then
					echo "You have busted with a value of $total"
					local stop_draw="true"
				fi
				;;
			"double"|"dub"|"w")
				echo "Attempting to double your bet and only get 1 more card"
				# Must only have 2 cards in your hand
				if [[ "${#player_hand[@]}" == 2 ]]; then
					local new_bank=$(( $bank - $bet_amount )) 
					debug "Attempting to set new bet amount in double"
					if [[ $new_bank -ge 0 ]]; then
						bank=$new_bank
						bet_amount=$(( $bet_amount * 2 ))
						debug "Set bank to $bank and bet_amount to $bet_amount"

						draw deck card
						local player_hand+=($card)
						echo "Player hand = ${player_hand[@]}"
						if [[ -z "${deck[@]}" ]]; then
							echo "deck is empty"
							deck=( $(draw_deck $NUM_OF_DECKS) )
						fi

						local stop_draw="true"

					else
						echo "You do not have enough money to double"
					fi
				else
					echo "You can only double when you have 2 cards"
				fi	
				;;
			"stand"|"stop"|"s")
				local total=$(hand_total "${player_hand[@]}")
				echo "You are standing with a value of $total"
				
				dealer_draw deck dealer_hand
				local dealer_total=$(hand_total "${dealer_hand[@]}")
				end_logic player_hand dealer_hand
				local game_result=$?
				# 2=player win; 3=dealer win; 4=push; 21=blackjack win 
				return $game_result
				
				;;
			"q"|"quit"|"exit")
				echo "leaving the program"
				return 0
				;;
			*)
				printf "Valid command not found\n'hit' or 'h' to add a card\n'double' or 'dub' to double your bet and get only 1 more card\n'stand' or 's' to stand\n'quit' or 'q' to quit the program\n"
		esac
	done
	return 0

}

function get_bet() {
	local -n amount_ref=$2
	local -n bank_ref=$1
	while true; do
		printf "Input valid bet: "
		read -r amount_ref;
		if [[ $amount_ref -gt $bank_ref ]]; then
			echo "Bet too large"
		elif [[ $amount_ref -lt 0 ]];then
			echo "Bet can't be negative"
		else
			bank_ref=$(( $bank_ref-$amount_ref ))
			return 0
		fi	
	done
}

function payout() {
	local -n bank_ref=$1
	local -n bet=$2
	local -n game_result_ref=$3

	case $game_result_ref in
		2)
			#echo "Player won"
			bank_ref=$(($bank_ref + ($bet * 2)))
			;;
		3)
			#echo "Dealer won"
			;;
		4)
			#echo "Push"
			bank_ref=$(($bank_ref + $bet))
			;;
		21)
			#Winning blackjack hand
			local new_winnings=$((($bet * 2) + $bet / 2))
			bank_ref=$(($bank_ref + $new_winnings))
			;;
		*)
			echo "There was an error somewhere"
			return 1
			;;
	esac
	return 0
}

function main() {
	if [[ -n $DEBUG ]]; then
		echo "--RUNNING IN DEBUG MODE--"
	fi
	bank=100
	while true; do
		echo "Starting cash $bank"
		get_bet bank bet_amount
		game
		local game_result=$?
		payout bank bet_amount game_result
		echo "Bank: $bank"
	done
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        echo "Running BlackJack"
	main
fi

