#!/usr/bin/env bash

. ./helper

function card_value() {
    local card=$1
    local card_value=${card:0:-1}


    case $card_value in
	    [[:digit:]]*)
	    echo "$card_value"
	    ;;
    	"A")
	    # Ace can be 1 or 11 
	    echo "11"
	    ;;
    	"J"|"Q"|"K")
	    echo "10"
	    ;;
	*)
	    echo "What kind of deck are you using"
	    ;;
    esac
}

function hand_total() {
	local hand=( "$@" )
	debug "Hand to total: ${hand[@]}"
	local total=0
	for card in "${hand[@]}"; do
		local curr_value=$(card_value $card) 
		local total=$(($total + $curr_value))
	done
	debug "Total before any manipulation: $total"
	# If hand contains ACE, subtract 10 if total > 21 

        local ace_present=$(printf -- '%s\n' "${hand[@]}" | grep "A")
        
	for ace in $ace_present; do
	    if [[ $total -gt 21 ]]; then
		debug "Total is too big if Ace is 11. Subtracting 10"
		total=$(( $total-10 ))
	    fi
	done
	
	echo "$total"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Running test code"
    declare -a arr=("AS" "AH" "9S")
    A_present=$(printf -- '%s\n' "${arr[@]}" | grep "A")
    
    if [[ -n $A_present ]]; then
	    echo "Ace present: $A_present"
    else 
	echo "No ace"
    fi

    echo "Full hand: ${arr[@]}"
    total=$(hand_total "${arr[@]}")
    echo "actual total: $total"
    card_value AD
    card_value 7S
    card_value 10D
    card_value KH
    card_value 2H
fi
