#!/usr/bin/env bash

. ./helper

function card_value() {
    local card=$1
    local card_value=${card:0:-1}


    case $card_value in
	    [[:digit:]]*)
	    echo "$card_value"
	    ;;
    	"A")
	    # Ace can be 1 or 11 
	    echo "11"
	    ;;
    	"J"|"Q"|"K")
	    echo "10"
	    ;;
	*)
	    echo "What kind of deck are you using"
	    ;;
    esac
}

function is_blackjack() {
	local hand=( "$@" )
	# Hmmm I wonder what the fastest way of checking this is

	debug "${hand[@]}"
	local arr_len="${#hand[@]}"
	if [[ arr_len -ne 2 ]]; then
		debug "Must be exactly 2 cards to be considered a blackjack, not $arr_len"
		echo "false"
		return 0
	fi
	
	local ace_present=$(printf -- '%s\n' "${hand[@]}" | grep "A")
	if [[ -z $ace_present ]]; then
		debug "Must contain and ace to be considered blackjack"
		echo "false"
		return 0
	fi

	local ten_present=$(printf -- '%s\n' "${hand[@]}" | grep -e "10" -e "J" -e "Q" -e "K")
	debug "ten_present: $ten_present"	
	if [[ -z $ten_present ]]; then
		debug "Must contain and 10 value to be considered blackjack"
		echo "false"
		return 0
	fi
	debug "Blackjack!"
	echo "true"
	return 0

}

function hand_total() {
	local hand=( "$@" )
	debug "Hand to total: ${hand[@]}"
	local total=0
	for card in "${hand[@]}"; do
		local curr_value=$(card_value $card) 
		local total=$(($total + $curr_value))
	done
	debug "Total before any manipulation: $total"
	# If hand contains ACE, subtract 10 if total > 21 

        local ace_present=$(printf -- '%s\n' "${hand[@]}" | grep "A")
        
	for ace in $ace_present; do
	    if [[ $total -gt 21 ]]; then
		debug "Total is too big if Ace is 11. Subtracting 10"
		total=$(( $total-10 ))
	    fi
	done
	
	echo "$total"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Running test code"
    declare -a arr=("AH" "9S")
    res=$(is_blackjack "${arr[@]}")
    echo "Result: $res"
    declare -a arr=("AH" "9S" "AS")
    res=$(is_blackjack "${arr[@]}")
    echo "Result: $res"
    declare -a arr=("KH" "AS")
    res=$(is_blackjack "${arr[@]}")
    echo "Result: $res"
    declare -a arr=("2S" "9S" "5H" "3D" "2D")
    res=$(is_blackjack "${arr[@]}")
    echo "Result: $res"
    declare -a arr=("AH" "KS")
    res=$(is_blackjack "${arr[@]}")
    echo "Result: $res"

fi
