#!/usr/bin/env bash

. ./shuffle
. ./card


function draw_deck() {
	local deck_num=$1
	local full_deck=$(build_deck $deck_num)
	local cards_arr=( $(shuf -e $full_deck) )
	echo ${cards_arr[@]}
}

function draw() {
	local -n deck_ref=$1
	local -n card_output=$2

	card_output="${deck_ref[0]}"	
	deck_ref=( "${deck_ref[@]:1}" )
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	echo "Running test code"
	deck=$(draw_deck 1)
	echo ${deck[@]}
	(deck_input "${deck[@]}")
fi
