#!/usr/bin/env bash


echo "Random"

random_num1="$(od -vAn -N1 -tu2 < /dev/urandom)"
echo "Random 1 byte unsigned integer: $random_num1"

random_num2="$(od -vAn -N1 -tu2 < /dev/urandom)"
echo "Random 1 byte unsigned integer: $random_num2"

plus=$(( random_num1 + random_num2 ))
echo "Random 1 byte plus another = $plus"

echo "Random mod 52: $(( plus % 52 ))"
