#!/usr/bin/env bash

# Constants
CARD_FILE="cards.txt"


function shuffle() {
    local full_deck=$1
    local deck=( $(shuf -e "${full_deck}") )
    echo ${deck[@]}
}


function build_deck() {
    local quan=$1
    local cards=$(cat $CARD_FILE)
    for i in $(seq 1 $quan); do
        echo "${cards[@]}"
    done
}

