#!/usr/bin/env bash

. ./art

# Stolen from YSAP's Nightful TUI
# https://github.com/bahamas10/nightfall-tui/blob/main/nightfall
# It is just a bash implementation of some tput commands to speed it up
# I added comments to each option to help me understand
tput() {
	local ESC=$'\x1b'
	case "$1" in
		sgr0) echo -n "$ESC[0m";; # Turn off all attributes
		bold) echo -n "$ESC[1m";; # Start bold text
		setaf) echo -n "$ESC[38;5;$2m";; # Set foreground color
		setab) echo -n "$ESC[48;5;$2m";; # Set foreground color
		sc) echo -n "$ESC[7";; # Save cursor position
		rc) echo -n "$ESC[8";; # Restore cursor position
		cnorm) echo -n "$ESC[?25h";; # Sets cursor to normal state
		civis) echo -n "$ESC[?25l";; # Set cursor to invisible
		smcup) echo -n "$ESC[?1049h";; #Saves screen contents
		rmcup) echo -n "$ESC[?1049l";; # Restores screen contents
		clear) echo -n "$ESC[2J";; # Clear the entires screen and home the cursor
		cup) # Moves curser to position
			local row=$(($2 + 1))
			local col=$(($3 + 1))
			echo -n "$ESC[$row;${col}H";;
		'') return 1;;
		*)
			# not implemented - default to external command
			command tput "$@"
			;;
	esac
}


function cleanup() {
	tput cnorm
	tput rmcup

	tput sgr0 # Reset color
	#stty echo 2>/dev/null
	return 0
}

function center_text_col() {
	local text=$1
	local text_len=${#text}
	echo "$((center_col-(text_len/2)))"
	return 0
}

function draw_ui() {
	draw_top 2
	local bottom_line=$(( $rows - 20 ))
	draw_table 2 $bottom_line
	
	local art_width=$(art_width "$BLACKJACK_ART")
	local starting_x="$((center_col-(art_width/2)))"
	print_art "$BLACKJACK_ART" $starting_x  20
		
	draw_bottom bottom_line
	draw_chip_stack
	return 0
}

function draw_horizontal_line() {
	local row=$1
	local char=$2
	local line=''
	for ((i=0; i < COLUMNS; i++)); do
		line+="$char"
	done

	tput cup $row 0
	echo -n "$line"
}

function draw_top() {
	local line=$1	
	local text="Dealer"
	
	tput cup 1 $(center_text_col $text)
	echo -n "$text"

	draw_horizontal_line 2 '─'

	return 0	
}

function draw_table() {
	local table_top=$(( $1 + 1 ))
	local table_bottom=$(( $2 - 1 ))

	for i in $(seq $table_top $table_bottom); do 
	#	echo "i: $i. top: $top_line. bot: $bottom_line"

		tput setab 2; draw_horizontal_line $i ' '
	done
	tput sgr0
}

function draw_chip_stack() {
	local chips=20
	local start_col=$(( $COLUMNS - 20 ))
	local start_row=$(( $rows - 10 ))
	print_chip_stack $(($chips / 100)) $start_col $start_row
	tput cup $(($start_row+1)) $start_col
	echo -n "Chips: $chips"
}

function draw_bottom() {
	local line=$1
	local text="Player: $USER"
	tput cup $(($rows - 1)) $(center_text_col $text) 
	echo -n "$text"

	draw_horizontal_line $line '─'
	return 0
}

function draw_input() {

	local start_col=10
	local start_row=$(( $rows - 11 ))
	print_art "$INPUT_BOX" $start_col $start_row
	#tput cup $(($start_col+1)) $(($start_row+1))
	tput cup 54 11
	echo -n "Action: "
	
}

function print_hand() {
	tput sc
	local is_player=$1
	local hand=( "${@:2}" )
	local hand_size="${#hand[@]}"
	local center_col=$(( $cols / 2 ))
	
	# This perfectly derived formula assumes that distance between cards is 2 and size of card is 4
	local starting_col=$(( $center_col - ( 2 * $hand_size + ( $hand_size - 2))))

	if [ "$1" == "player" ]; then
		local row=40
	elif [ "$1" == "dealer" ]; then
		local row=10
	else	
		echo "Something went wrong "
	fi
	local affected_rows=$(($row+2))
	for i in $(seq $row $affected_rows);do
		draw_horizontal_line $i ' '
	done


	for card in "${hand[@]}"; do
		print_card $card starting_col row
		starting_col=$(( $starting_col+6 ))
	done
	tput rc

}

function clear_input() {
	local start_col=11
	local start_row=$(( $rows - 10 ))

	tput cup $start_row $start_col
        echo -n "Action:               "
	tput cup $start_row $(( $start_col + 8 ))

}

function clear_table() {
	local table_top=$(( $1 + 1 ))
	local table_bottom=$(( $2 - 1 ))

	for i in $(seq $table_top $table_bottom); do 
	#	echo "i: $i. top: $top_line. bot: $bottom_line"

		tput setab 2; draw_horizontal_line $i ' '
	done
	tput sgr0
}


shopt -s checkwinsize
(:)
cols=$COLUMNS
rows=$LINES


function main() {
	echo "Running the UI"

	center_row=$((rows/2))
	center_col=$((cols/2))
	

	echo "Terminal size ${rows}x${cols}"

	trap cleanup exit

	tput smcup
	tput civis
	#stty -echo

	#text="This is the center"
	#text_len=${#text}
	#tput cup $center_row $((center_col-(text_len/2)))
	#echo -n "This is the center"
	
	draw_ui
	
	#Example Player hand
	print_card "AS" 50 40
	print_card "KH" 56 40
	
	# Example dealer hand
	print_card "6S" 41 10
	print_card "2S" 47 10
	print_card "4H" 53 10
	print_card "10D" 59 10
	
	draw_input
	local bottom_line=$(( $rows - 20 ))

	while read -ra data; do
		#echo "data: $data"
		if [[ $data = "clear" ]]; then
			draw_table 2 $bottom_line
	
		fi
		clear_input
		
	done;
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	echo "Running UI"
	main
fi


# Various tput commands
# tput sc #Saves the curor location
# rpur cup "COL" "LINE" #Moves the curser to COL x Line position
# tput setaf NUM #Sets foreground color
#
#
# to get pid of previously run background task
# local pid=$!
# wait "$pid" #Waits until the pid task is closed/exited
